#name : Template POD
# --
$0
=head1 NAME

${1:`(yas/perl-package-name)`} -

=head1 SYNOPSIS

=head1 DESCRIPTION

$1 is

=head1 AUTHOR

Syohei YOSHIDA E<lt>syohex@gmail.comE<gt>

=head1 COPYRIGHT

Copyright `(format-time-string "%Y")` - Syohei YOSHIDA

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
