;; setting for eshell
(defvar eshell-pop-buffer "*eshell pop*")
(defun eshell-pop ()
  (interactive)
  (let ((buf (get-buffer eshell-pop-buffer)))
    (when (buffer-live-p buf)
      (kill-buffer buf))
    (with-current-buffer (get-buffer-create eshell-pop-buffer)
      (let ((eshell-banner-message ""))
        (eshell-mode)
        (pop-to-buffer (current-buffer))))))
(global-set-key (kbd "M-g M-s") 'eshell-pop)
