(source gnu)
(source melpa)

;; auto-complete
(depends-on "auto-complete")
(depends-on "fuzzy")
(depends-on "popup")
;;(depends-on "pos-tip")

;; Editing
(depends-on "thingopt")

;; region
(depends-on "expand-region")
(depends-on "wrap-region")

;; undo
(depends-on "undo-tree")

;; highlight
(depends-on "vline")
(depends-on "col-highlight")

;; snippet
(depends-on "yasnippet")

;; cursor
(depends-on "goto-chg")
(depends-on "ace-jump-mode")

;; buffer
(depends-on "elscreen" :git "https://github.com/emacs-jp/elscreen.git" :branch "fixed")
(depends-on "popwin")
(depends-on "buffer-move")
(depends-on "ace-jump-buffer")

;; Window
;;;(depends-on "zoom-window" :git "https://github.com/syohex/emacs-zoom-window.git")

;; Key utility
(depends-on "smartrep")

;; Scroll bar
(depends-on "yascroll")

;; Haskell
(depends-on "haskell-mode")
(depends-on "ghc")

;; CoffeeScript
(depends-on "coffee-mode")
(depends-on "sourcemap")

;; Perl
(depends-on "cperl-mode")
(depends-on "xs-mode" :git "https://github.com/emacsmirror/xs-mode.git")

;; Go
(depends-on "go-mode")

;; Python
(depends-on "jedi")

;; Ruby
(depends-on "ruby-block")
(depends-on "ruby-compilation")
(depends-on "ruby-end")
(depends-on "ruby-interpolation")
(depends-on "ruby-mode")
(depends-on "ruby-test-mode")
(depends-on "ruby-tools")
(depends-on "inf-ruby")

;; Programming Misc
(depends-on "autopair")
(depends-on "rainbow-mode")

;; Emacs Lisp
(depends-on "elisp-slime-nav")
(depends-on "paredit")

;; Common Lisp
(depends-on "slime")
;;(depends-on "scheme-complete")

;; Validation
(depends-on "flycheck")

;; Shell
(depends-on "quickrun")

;; Markup language
(depends-on "web-mode")
(depends-on "emmet-mode")
(depends-on "yaml-mode")
(depends-on "less-css-mode")

;; markdown
(depends-on "markdown-mode")

;; helm
(depends-on "helm")

;; VCS
(depends-on "magit")
(depends-on "git-gutter")

;; Directory
(depends-on "dired-k")
(depends-on "direx")

;; Documentation
(depends-on "zeal-at-point")

;; Setup
(depends-on "init-loader")
(depends-on "exec-path-from-shell")

;; Theme
(depends-on "reverse-theme")

;; Search
(depends-on "anzu")

;; clojure
(depends-on "clojure-mode")
(depends-on "cider")

;; shell
(depends-on "shell-pop")

;; sub packages

;;;; auto-complete sources
(depends-on "ac-slime")
(depends-on "ac-nrepl")
(depends-on "go-autocomplete")
(depends-on "ac-ispell")
(depends-on "ac-etags")
(depends-on "robe")
(depends-on "ac-c-headers")

;;;; popwin
(depends-on "import-popwin")

;;;; go-mode
(depends-on "go-eldoc")
(depends-on "helm-godoc" :git "https://github.com/syohex/emacs-helm-godoc.git")
(depends-on "golint")

;;;; helm
(depends-on "helm-swoop")
(depends-on "helm-gtags")
(depends-on "helm-descbinds")
(depends-on "helm-ag")
(depends-on "helm-pydoc")
(depends-on "helm-perldoc")
(depends-on "helm-open-github")

;; My own tools
(depends-on "editutil" :git "https://github.com/syohex/emacs-editutil.git")
(depends-on "sgit" :git "https://github.com/syohex/emacs-sgit.git")
